### ISSUE TITLE
[회의] 1주차 미팅 논의 사항

### ISSUE THREAD

**Issue by teang1995** [OwO-CR/OWOCR#3]
1. 이슈 관리? 
2. PEP8 체크에 github action 도입? -> 다른 것도 도입할 수 있을 듯?
3. 코멘트로 추가 요망

**Comment by GiDaeHyeon** [comment]
깃 커밋 메시지 작성 룰도 지켜냅시다!

**Comment by Seonghoon-Yu** [comment]
> 깃 커밋 메시지 작성 룰도 지켜냅시다!

넹

**Comment by teang1995** [comment]
# 첫 번째 회의록

## 논의 사항
### 1. 매주 무엇을 할 지?
회사 일을 제외한 공부.
회사 일을 위한 공부도 가능.


### 2. 언제를 기점으로 1주를 잡을 지?
일요일에 서로의 코드를 보며 비난하며 한 주를 마무리한다.
일요일 저녁에 약속이 있는 사람이 많진 않을까?
우린 그렇게 인싸가 아니다. + 당신들이 그렇게 규칙적인가? 나대지말고 **저녁 10시**로 하자. 


### 3. 가봉은 어디 갔는지?
앞으로 이렇게 잠적하면 매질을 해야 함.
회사 위치를 알고 마침 한가한 대현님이 잠복 후 가격 예정.


### 4. 커밋 메세지 어떻게 정의할지?
[how to write commit message?](https://richone.tistory.com/26)
이 정도의 규칙을 따르면 크게 겐세이(?) 넣을 일은 없어보인다.
추가적인 규칙이 필요하다면 회의 시간에 논의 하도록 하자.
이것 또한 코드 리뷰 할 때 논의할 수 있는 요소.

eg)
issue #37 
여기에 관련된 커밋을 한다.
"[#37] commit message"
이렇게 커밋 메세지를 작성하면
커밋을 자동으로 이슈에 포함시켜줌.


### 5. Branch 관리?
$name/$contents 처럼 브랜치명을 만들고,
eg) 
yongtaek/BentoML
jeongtae/Scalar

해당 부분 공부가 마무리되면 merge 후 브랜치 삭제.


### 6. 이슈를 주마다 작성해서 TODO list를 관리하는 식으로 하면 어떨까?(제안)
[issue TODO's eg](https://github.com/OwO-CR/OWOCR/issues/2)
해보자.

**Comment by Seonghoon-Yu** [comment]
깔-끔 하게 정리해주셔서 감사합니당
